export const financeKeys = {
  all: ['finance'] as const,
  transactions: () => [...financeKeys.all, 'transactions'] as const,
  transactionList: (filters?: Record<string, string>) =>
    [...financeKeys.transactions(), 'list', filters] as const,
  todayTotal: () => [...financeKeys.transactions(), 'today-total'] as const,
  budgets: () => [...financeKeys.all, 'budgets'] as const,
  budgetSummary: (month: string) => [...financeKeys.budgets(), 'summary', month] as const,
  bills: () => [...financeKeys.all, 'bills'] as const,
  billList: () => [...financeKeys.bills(), 'list'] as const,
  upcomingBills: (days?: number) => [...financeKeys.bills(), 'upcoming', days ?? 30] as const,
  goals: () => [...financeKeys.all, 'goals'] as const,
  goalList: () => [...financeKeys.goals(), 'list'] as const,
  wallets: () => [...financeKeys.all, 'wallets'] as const,
  walletList: () => [...financeKeys.wallets(), 'list'] as const,
  transfers: () => [...financeKeys.all, 'transfers'] as const,
  transferList: () => [...financeKeys.transfers(), 'list'] as const,
  categories: () => [...financeKeys.all, 'categories'] as const,
  categoryList: () => [...financeKeys.categories(), 'list'] as const,
  imports: () => [...financeKeys.all, 'imports'] as const,
  importList: () => [...financeKeys.imports(), 'list'] as const,
  importDetail: (id: string) => [...financeKeys.imports(), 'detail', id] as const,
  analytics: () => [...financeKeys.all, 'analytics'] as const,
  analyticsQuery: (name: string, filters?: Record<string, string | number | undefined>) =>
    [...financeKeys.analytics(), name, filters] as const,
}