/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated/habits'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedFinanceIndexRouteImport } from './routes/_authenticated/finance/index'
import { Route as AuthenticatedFinanceWalletsRouteImport } from './routes/_authenticated/finance/wallets'
import { Route as AuthenticatedFinanceGoalsRouteImport } from './routes/_authenticated/finance/goals'
import { Route as AuthenticatedFinanceCategoriesRouteImport } from './routes/_authenticated/finance/categories'
import { Route as AuthenticatedFinanceBudgetRouteImport } from './routes/_authenticated/finance/budget'
import { Route as AuthenticatedFinanceBillsRouteImport } from './routes/_authenticated/finance/bills'
import { Route as AuthenticatedFinanceAnalyticsRouteImport } from './routes/_authenticated/finance/analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceIndexRoute =
  AuthenticatedFinanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceWalletsRoute =
  AuthenticatedFinanceWalletsRouteImport.update({
    id: '/wallets',
    path: '/wallets',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceGoalsRoute =
  AuthenticatedFinanceGoalsRouteImport.update({
    id: '/goals',
    path: '/goals',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceCategoriesRoute =
  AuthenticatedFinanceCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceBudgetRoute =
  AuthenticatedFinanceBudgetRouteImport.update({
    id: '/budget',
    path: '/budget',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceBillsRoute =
  AuthenticatedFinanceBillsRouteImport.update({
    id: '/bills',
    path: '/bills',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceAnalyticsRoute =
  AuthenticatedFinanceAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/habits': typeof AuthenticatedHabitsRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/finance/analytics': typeof AuthenticatedFinanceAnalyticsRoute
  '/finance/bills': typeof AuthenticatedFinanceBillsRoute
  '/finance/budget': typeof AuthenticatedFinanceBudgetRoute
  '/finance/categories': typeof AuthenticatedFinanceCategoriesRoute
  '/finance/goals': typeof AuthenticatedFinanceGoalsRoute
  '/finance/wallets': typeof AuthenticatedFinanceWalletsRoute
  '/finance/': typeof AuthenticatedFinanceIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/': typeof AuthenticatedIndexRoute
  '/finance/analytics': typeof AuthenticatedFinanceAnalyticsRoute
  '/finance/bills': typeof AuthenticatedFinanceBillsRoute
  '/finance/budget': typeof AuthenticatedFinanceBudgetRoute
  '/finance/categories': typeof AuthenticatedFinanceCategoriesRoute
  '/finance/goals': typeof AuthenticatedFinanceGoalsRoute
  '/finance/wallets': typeof AuthenticatedFinanceWalletsRoute
  '/finance': typeof AuthenticatedFinanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/_authenticated/habits': typeof AuthenticatedHabitsRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/finance/analytics': typeof AuthenticatedFinanceAnalyticsRoute
  '/_authenticated/finance/bills': typeof AuthenticatedFinanceBillsRoute
  '/_authenticated/finance/budget': typeof AuthenticatedFinanceBudgetRoute
  '/_authenticated/finance/categories': typeof AuthenticatedFinanceCategoriesRoute
  '/_authenticated/finance/goals': typeof AuthenticatedFinanceGoalsRoute
  '/_authenticated/finance/wallets': typeof AuthenticatedFinanceWalletsRoute
  '/_authenticated/finance/': typeof AuthenticatedFinanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/finance'
    | '/habits'
    | '/auth/verify'
    | '/finance/analytics'
    | '/finance/bills'
    | '/finance/budget'
    | '/finance/categories'
    | '/finance/goals'
    | '/finance/wallets'
    | '/finance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/habits'
    | '/auth/verify'
    | '/'
    | '/finance/analytics'
    | '/finance/bills'
    | '/finance/budget'
    | '/finance/categories'
    | '/finance/goals'
    | '/finance/wallets'
    | '/finance'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/finance'
    | '/_authenticated/habits'
    | '/auth/verify'
    | '/_authenticated/'
    | '/_authenticated/finance/analytics'
    | '/_authenticated/finance/bills'
    | '/_authenticated/finance/budget'
    | '/_authenticated/finance/categories'
    | '/_authenticated/finance/goals'
    | '/_authenticated/finance/wallets'
    | '/_authenticated/finance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/': {
      id: '/_authenticated/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/wallets': {
      id: '/_authenticated/finance/wallets'
      path: '/wallets'
      fullPath: '/finance/wallets'
      preLoaderRoute: typeof AuthenticatedFinanceWalletsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/goals': {
      id: '/_authenticated/finance/goals'
      path: '/goals'
      fullPath: '/finance/goals'
      preLoaderRoute: typeof AuthenticatedFinanceGoalsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/categories': {
      id: '/_authenticated/finance/categories'
      path: '/categories'
      fullPath: '/finance/categories'
      preLoaderRoute: typeof AuthenticatedFinanceCategoriesRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/budget': {
      id: '/_authenticated/finance/budget'
      path: '/budget'
      fullPath: '/finance/budget'
      preLoaderRoute: typeof AuthenticatedFinanceBudgetRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/bills': {
      id: '/_authenticated/finance/bills'
      path: '/bills'
      fullPath: '/finance/bills'
      preLoaderRoute: typeof AuthenticatedFinanceBillsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/analytics': {
      id: '/_authenticated/finance/analytics'
      path: '/analytics'
      fullPath: '/finance/analytics'
      preLoaderRoute: typeof AuthenticatedFinanceAnalyticsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
  }
}

interface AuthenticatedFinanceRouteChildren {
  AuthenticatedFinanceAnalyticsRoute: typeof AuthenticatedFinanceAnalyticsRoute
  AuthenticatedFinanceBillsRoute: typeof AuthenticatedFinanceBillsRoute
  AuthenticatedFinanceBudgetRoute: typeof AuthenticatedFinanceBudgetRoute
  AuthenticatedFinanceCategoriesRoute: typeof AuthenticatedFinanceCategoriesRoute
  AuthenticatedFinanceGoalsRoute: typeof AuthenticatedFinanceGoalsRoute
  AuthenticatedFinanceWalletsRoute: typeof AuthenticatedFinanceWalletsRoute
  AuthenticatedFinanceIndexRoute: typeof AuthenticatedFinanceIndexRoute
}

const AuthenticatedFinanceRouteChildren: AuthenticatedFinanceRouteChildren = {
  AuthenticatedFinanceAnalyticsRoute: AuthenticatedFinanceAnalyticsRoute,
  AuthenticatedFinanceBillsRoute: AuthenticatedFinanceBillsRoute,
  AuthenticatedFinanceBudgetRoute: AuthenticatedFinanceBudgetRoute,
  AuthenticatedFinanceCategoriesRoute: AuthenticatedFinanceCategoriesRoute,
  AuthenticatedFinanceGoalsRoute: AuthenticatedFinanceGoalsRoute,
  AuthenticatedFinanceWalletsRoute: AuthenticatedFinanceWalletsRoute,
  AuthenticatedFinanceIndexRoute: AuthenticatedFinanceIndexRoute,
}

const AuthenticatedFinanceRouteWithChildren =
  AuthenticatedFinanceRoute._addFileChildren(AuthenticatedFinanceRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRouteWithChildren
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFinanceRoute: AuthenticatedFinanceRouteWithChildren,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
