import 'fake-indexeddb/auto'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { clear, createStore } from 'idb-keyval'
import {
  enqueue,
  dequeue,
  getAll,
  getAllFailed,
  markFailed,
  markPending,
  incrementRetry,
  getCorruptCount,
  discardCorrupt,
  type QueuedMutation,
} from './mutation-queue'

// idb-keyval keeps its connections open, so deleteDatabase would block.
// Clearing both stores between tests is reliable and fast; a store that was
// never written yet doesn't exist, so tolerate the miss.
async function resetStores() {
  for (const [db, name] of [['my-sync','mutations'], ['my-sync-corrupt','corrupt']] as const) {
    try {
      await clear(createStore(db, name))
    } catch {
      // store not created yet — nothing to clear
    }
  }
}

function entry(overrides: Partial<Omit<QueuedMutation, 'id'>> = {}): Omit<QueuedMutation, 'id'> {
  return {
    schemaVersion: 1,
    method: 'POST',
    url: '/api/v1/test',
    body: JSON.stringify({ ok: true }),
    createdAt: new Date().toISOString(),
    retries: 0,
    maxRetries: 5,
    state: 'pending',
    failedReason: null,
    failedAt: null,
    ...overrides,
  }
}

describe('mutation-queue', () => {
  beforeEach(async () => {
    await resetStores()
  })

  afterEach(async () => {
    await resetStores()
  })

  it('persists an enqueued mutation and lists it FIFO', async () => {
    // createdAt is generated by enqueue; FIFO is verified by insertion order.
    const first = await enqueue(entry())
    const second = await enqueue(entry())

    const all = await getAll()
    expect(all).toHaveLength(2)
    expect(all[0]!.id).toBe(first)
    expect(all[1]!.id).toBe(second)
  })

  it('dequeues by id', async () => {
    const id = await enqueue(entry())
    await dequeue(id)
    expect(await getAll()).toHaveLength(0)
  })

  it('marks failed and surfaces it in getAllFailed, not getAll', async () => {
    const id = await enqueue(entry())
    await markFailed(id, 'HTTP 422')

    const pending = await getAll()
    const failed = await getAllFailed()
    expect(pending).toHaveLength(0)
    expect(failed).toHaveLength(1)
    expect(failed[0]!.failedReason).toBe('HTTP 422')
    expect(failed[0]!.failedAt).not.toBeNull()
  })

  it('markPending returns a dead letter to the pending queue and resets retries', async () => {
    const id = await enqueue(entry())
    await markFailed(id, 'HTTP 400')
    await incrementRetry(id)
    await markPending(id)

    const pending = await getAll()
    expect(pending).toHaveLength(1)
    expect(pending[0]!.retries).toBe(0)
    expect(pending[0]!.failedReason).toBeNull()
    expect(await getAllFailed()).toHaveLength(0)
  })

  it('incrementRetry never deletes, even at max retries', async () => {
    const id = await enqueue(entry())
    for (let i = 0; i < 10; i++) {
      await incrementRetry(id)
    }
    // Exhaustion is the caller's decision (markFailed) — the entry must
    // still exist.
    const pending = await getAll()
    expect(pending).toHaveLength(1)
    expect(pending[0]!.retries).toBe(10)
  })

  it('parses legacy entries without the dead-letter fields (no schema wipe)', async () => {
    const id = await enqueue(entry())
    // Simulate an entry persisted before the state fields existed.
    const { get, set } = await import('idb-keyval')
    const store = (await import('idb-keyval')).createStore('my-sync', 'mutations')
    const raw = await get(id, store)
    const { state, failedReason, failedAt, ...legacy } = raw as QueuedMutation
    await set(id, legacy, store)

    const pending = await getAll()
    expect(pending).toHaveLength(1)
    expect(pending[0]!.state).toBe('pending')
  })

  it('parks unparseable entries in the corrupt store instead of deleting', async () => {
    const { set } = await import('idb-keyval')
    const store = (await import('idb-keyval')).createStore('my-sync', 'mutations')
    await set('bad-key', { nope: true }, store)

    expect(await getAll()).toHaveLength(0)
    expect(await getCorruptCount()).toBe(1)
    expect(await getAllFailed()).toHaveLength(0)

    await discardCorrupt()
    expect(await getCorruptCount()).toBe(0)
  })
})
