root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api"
entrypoint = ["./tmp/main"]
include_ext = ["go", "sql"]
exclude_dir = ["tmp", "vendor", "scripts"]
exclude_regex = ["_test\\.go$"]
delay = 500

[log]
time = true

[color]
main = "cyan"
watcher = "green"
build = "yellow"

[proxy]
enabled = true
proxy_port = 8090
app_port = 8080
app_start_timeout = 5000